### ISSUE TITLE
Package Restyling

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/api_gateway#10]
The changes to be applied during the restyling process are:
- [x] Replace a plain `requirements_dev.txt` file for development by the use of the `Poetry` package manager: https://github.com/Clariteia/minos-pypackage/issues/4
- [x] Improve `codecov` config to allow a small degree of tolerance: https://github.com/Clariteia/minos-pypackage/issues/5
- [x] Integrate `pre-commit`: https://github.com/Clariteia/minos-pypackage/issues/6
- [x] Configure `restyled`: https://github.com/Clariteia/minos-pypackage/issues/7
- [x] Update GitHub Actions structure: https://github.com/Clariteia/minos-pypackage/issues/8
- [x] Integrate `flake8` at `pre-commit` and Github Actions level: https://github.com/Clariteia/minos-pypackage/issues/9
- [x] Automate documentation generation and publish on GitHub Pages: https://github.com/Clariteia/minos-pypackage/issues/10

**Comment by garciparedes** [comment]
In order to ease the restyling process, I recommend to see the applied changes on this Pull Request: https://github.com/Clariteia/minos_microservice_common/pull/222
